# .github/workflows/gpt-translate.yml
name: Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Adding README - Español
        uses: AchrafBr1/translate-readme@main
        with:
          LANG: es
