name: Translate

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if already running
        id: check_running
        run: echo "Already running" && test -e /tmp/translate_lock

      - name: Skip if already running
        if: steps.check_running.outputs.result == 'Already running'
        run: exit 0

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Imprimir nombre detectado
        run: echo "${{ github.event.comment.body }}"
        
      - name: A単adiendo ${{ github.event.comment.body }} - Espa単ol
        uses: AchrafBr1/translate-readme@main
        with:
          LANG: es
          MODEL: ${{ github.event.comment.body }}
          
      - name: A単adiendo ${{ github.event.comment.body }} - Frances
        uses: AchrafBr1/translate-readme@main
        with:
          LANG: fr
          MODEL: ${{ github.event.comment.body }}

      - name: A単adiendo ${{ github.event.comment.body }} - Italiano
        uses: AchrafBr1/translate-readme@main
        with:
          LANG: it
          MODEL: ${{ github.event.comment.body }}

      - name: Mark workflow as running
        run: echo "Running" > /tmp/translate_lock

      # Your other steps go here

      - name: Cleanup - Remove lock
        run: rm -f /tmp/translate_lock

  queue:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for lock release
        id: wait_for_lock
        run: echo "Waiting for lock" && test -e /tmp/translate_lock
      - name: Check if workflow completed
        id: check_workflow
        run: echo "Workflow completed" && gh run list --json status | jq '.workflow_runs[0].status' | grep -q 'completed'
      - name: Release lock if previous workflow completed
        if: steps.check_workflow.outputs.status == 'completed'
        run: rm -f /tmp/translate_lock
